version: "3.7"

services: 
  database: 
    image: postgres
    container_name: database_vuttr
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=vuttr
      - POSTGRES_DB=vuttr
    volumes: 
      - pgdata:/data/postgres
    
volumes: 
  pgdata:
    driver: local