version: "3.7"

services: 
  database: 
    image: postgres
    container_name: database_vuttr
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=vuttr
      - POSTGRES_DB=vuttr
    volumes: 
      - pgdata:/data/postgres
  
  app: 
    build: .
    container_name: vuttr
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on: 
      - database
      
volumes: 
  pgdata:
    driver: local